[package]
name = "event"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
lazy_static = "1.5.0"
tokio = { version = "1.47.1", features = ["full","rt-multi-thread"] }
inventory = "0.3"
once_cell = "1.21.3"
[dev-dependencies]
anyhow = "1.0.98"